# Generated by Django 4.0.3 on 2022-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
