# Generated by Django 4.0.3 on 2022-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='variant',
            field=models.CharField(choices=[('dummy', 'dummy')], max_length=255),
        ),
    ]
