# Generated by Django 4.0.3 on 2022-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_payment_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
