# Generated by Django 4.0.3 on 2022-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_order_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='variant',
            field=models.CharField(choices=[('default', 'default')], max_length=255),
        ),
    ]
