# Generated by Django 4.0.3 on 2022-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_order_sum_alter_payment_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='variant',
            field=models.CharField(max_length=255),
        ),
    ]
