# Generated by Django 4.0.3 on 2022-03-16 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 3, 16, 22, 25, 32, 739523, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
