# Generated by Django 4.0.3 on 2022-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
    ]
